# Generated by Django 5.1.4 on 2025-02-23 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=17)),
                (
                    "currency",
                    models.CharField(
                        choices=[("NGN", "Ngn"), ("USD", "Usd")], max_length=20
                    ),
                ),
                ("transaction_id", models.CharField(max_length=100, unique=True)),
                ("verified", models.BooleanField(default=False)),
                ("expiration_date", models.DateTimeField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="order.order"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Payments",
                "ordering": ["timestamp"],
            },
        ),
    ]
